#include "V2XTaskApp.h"
#include "KfGinsController.h"
#include <fstream>
#include <sstream>
#include <random>
#include <algorithm>
#include <cmath>
Define_Module(V2XTaskApp);
static std::mt19937 rng(42);
static double uniform(double a,double b){std::uniform_real_distribution<double>d(a,b);return d(rng);} 
void V2XTaskApp::loadTrace(const std::string& path){std::ifstream in(path); if(!in.is_open()) throw cRuntimeError("Cannot open trajectory file: %s",path.c_str()); std::string line; std::getline(in,line); while(std::getline(in,line)){ if(line.empty()) continue; std::stringstream ss(line); std::string item; std::vector<std::string> cols; while(std::getline(ss,item,',')) cols.push_back(item); if(cols.size()<5) continue; try{TraceRow r; r.time=std::stod(cols[0]); r.vehicleId=cols[1]; r.x=std::stod(cols[2]); r.y=std::stod(cols[3]); r.speed=std::stod(cols[4]); traceRows.push_back(r);}catch(...){}} if(traceRows.empty()) throw cRuntimeError("trajectory.csv contains no valid rows");}
void V2XTaskApp::loadLinkTrace(const std::string& path){std::ifstream in(path); if(!in.is_open()) throw cRuntimeError("Cannot open link trace file: %s",path.c_str()); std::string line; std::getline(in,line); while(std::getline(in,line)){ if(line.empty()) continue; std::stringstream ss(line); std::string item; std::vector<std::string> cols; while(std::getline(ss,item,',')) cols.push_back(item); if(cols.size()<7) continue; try{LinkTraceRow r; r.time=std::stod(cols[0]); r.vehicleId=cols[1]; r.uplinkMbps=std::stod(cols[2]); r.downlinkMbps=std::stod(cols[3]); r.mecQueueS=std::stod(cols[4]); r.nextHoS=std::stod(cols[5]); r.hoActive=std::stoi(cols[6]); linkRows.push_back(r);}catch(...){}} if(linkRows.empty()) throw cRuntimeError("link_trace.csv contains no valid rows");}
const LinkTraceRow& V2XTaskApp::nextLinkRow(){const LinkTraceRow& row=linkRows[linkIndex%linkRows.size()]; linkIndex++; return row;}
double V2XTaskApp::distanceToCellBoundary(double x,double y,double cellSize){double xCell=std::floor(x/cellSize)*cellSize; double yCell=std::floor(y/cellSize)*cellSize; double dLeft=x-xCell,dRight=xCell+cellSize-x,dBottom=y-yCell,dTop=yCell+cellSize-y; return std::max(0.5,std::min(std::min(dLeft,dRight),std::min(dBottom,dTop)));}
void V2XTaskApp::initialize(){timer=new cMessage("taskTimer"); loadTrace(par("tracePath").stringValue()); loadLinkTrace(par("linkTracePath").stringValue()); std::ofstream out("results_task_log.csv"); out<<"algorithm,task_id,time,vehicle_id,x,y,distance_to_boundary,speed,gnss_sigma,uplink_mbps,downlink_mbps,mec_queue_s,next_ho_s,input_MB,output_MB,cycles,t_up,t_queue,t_exec,t_down,T_edge,T_local,deadline,tau_HO_hat,mu_G,sigma_G,margin,decision,success,fail_reason\n"; out.close(); scheduleAt(simTime()+par("taskInterval").doubleValue(),timer);} 
void V2XTaskApp::handleMessage(cMessage *msg){ if(msg!=timer) return; double t=simTime().dbl(); int startOffset=std::min(1000,(int)traceRows.size()-1); const TraceRow& row=traceRows[(startOffset+traceIndex*10)%traceRows.size()]; traceIndex++; const LinkTraceRow& link=nextLinkRow(); double cellSize=par("cellSize").doubleValue(); double dBoundary=distanceToCellBoundary(row.x,row.y,cellSize); double speed=std::max(0.1,row.speed); double gnssSigma=par("gnssSigma").doubleValue(); std::string alg=par("algorithm").stdstringValue(); double inputMB=uniform(0.6,1.8), outputMB=uniform(0.05,0.25), cycles=uniform(0.8e9,2.5e9); double tUp=inputMB/std::max(0.1,link.uplinkMbps), tQueue=link.mecQueueS, tExec=cycles/30e9, tDown=outputMB/std::max(0.1,link.downlinkMbps); double tEdge=tUp+tQueue+tExec+tDown, tLocal=cycles/3.4e9; double deadline=1.00, tauHoHat=link.nextHoS, tGuard=0.26; if(link.hoActive==1) tauHoHat=0.0; KfGinsController controller; KfGinsDecision d=controller.decide({dBoundary,speed,gnssSigma,tEdge,tLocal,deadline,tauHoHat,tGuard}); if(alg=="nearest_rtt"){d.offload=(tEdge<tLocal)&&(tEdge<=deadline); d.muG=dBoundary-speed*tEdge; d.sigmaG=0; d.margin=d.muG;} else if(alg=="risk_no_cov"){d.offload=(tEdge<=deadline)&&(tEdge+tGuard<=tauHoHat)&&(d.muG>=0);} else if(alg!="kfgins_risk") throw cRuntimeError("Unknown algorithm: %s",alg.c_str()); bool success=false; std::string reason; if(d.offload){double actualUncertainty=uniform(0,0.80*gnssSigma); double actualMargin=dBoundary-speed*tEdge-actualUncertainty; success=(tEdge<=deadline)&&(actualMargin>=0); reason=success?"success":"handover_or_deadline_failure";} else {success=(tLocal<=deadline); reason=success?"success":"local_deadline_miss";} std::ofstream out("results_task_log.csv",std::ios::app); out<<alg<<","<<taskId<<","<<t<<","<<row.vehicleId<<","<<row.x<<","<<row.y<<","<<dBoundary<<","<<speed<<","<<gnssSigma<<","<<link.uplinkMbps<<","<<link.downlinkMbps<<","<<link.mecQueueS<<","<<link.nextHoS<<","<<inputMB<<","<<outputMB<<","<<cycles<<","<<tUp<<","<<tQueue<<","<<tExec<<","<<tDown<<","<<tEdge<<","<<tLocal<<","<<deadline<<","<<tauHoHat<<","<<d.muG<<","<<d.sigmaG<<","<<d.margin<<","<<(d.offload?"edge":"local")<<","<<(success?1:0)<<","<<reason<<"\n"; taskId++; scheduleAt(simTime()+par("taskInterval").doubleValue(),timer);} 
void V2XTaskApp::finish(){cancelAndDelete(timer);} 
