#include "LinkTraceLogger.h"
#include <cmath>
#include <algorithm>
Define_Module(LinkTraceLogger);
void LinkTraceLogger::initialize(){outputPath=par("outputPath").stdstringValue(); interval=par("interval").doubleValue(); out.open(outputPath,std::ios::out); if(!out.is_open()) throw cRuntimeError("Cannot open link trace output file: %s",outputPath.c_str()); ulSignals.insert(registerSignal("packetSent")); ulSignals.insert(registerSignal("packetSentToLower")); ulSignals.insert(registerSignal("packetPushed")); ulSignals.insert(registerSignal("packetSentSignal")); dlSignals.insert(registerSignal("packetReceived")); dlSignals.insert(registerSignal("packetReceivedFromLower")); dlSignals.insert(registerSignal("packetPulled")); dlSignals.insert(registerSignal("packetReceivedSignal")); hoStartSignals.insert(registerSignal("handoverStart")); hoStartSignals.insert(registerSignal("handoverTriggered")); hoStartSignals.insert(registerSignal("handoverCommand")); hoEndSignals.insert(registerSignal("handoverEnd")); hoEndSignals.insert(registerSignal("handoverComplete")); hoEndSignals.insert(registerSignal("handoverCompleted")); kfginsHoStartSig=registerSignal("kfginsHoStart"); kfginsHoEndSig=registerSignal("kfginsHoEnd"); kfginsNextHoSig=registerSignal("kfginsNextHoS"); kfginsMecQueueDelaySig=registerSignal("kfginsMecQueueDelay"); subscribeRecursively(getSimulation()->getSystemModule()); writeHeader(); timer=new cMessage("linkTraceTimer"); scheduleAt(simTime(),timer);} 
void LinkTraceLogger::subscribeRecursively(cModule *module){if(!module)return; for(auto sig:ulSignals) module->subscribe(sig,this); for(auto sig:dlSignals) module->subscribe(sig,this); for(auto sig:hoStartSignals) module->subscribe(sig,this); for(auto sig:hoEndSignals) module->subscribe(sig,this); module->subscribe(kfginsHoStartSig,this); module->subscribe(kfginsHoEndSig,this); module->subscribe(kfginsNextHoSig,this); module->subscribe(kfginsMecQueueDelaySig,this); for(cModule::SubmoduleIterator it(module);!it.end();++it) subscribeRecursively(*it);} 
void LinkTraceLogger::receiveSignal(cComponent *source,simsignal_t signalID,cObject *obj,cObject *details){cPacket *pkt=dynamic_cast<cPacket*>(obj); if(pkt){long bytes=pkt->getByteLength(); std::string path=source?source->getFullPath():""; if(path.find("ue")!=std::string::npos||path.find("UE")!=std::string::npos) ulBytes+=bytes; else if(path.find("server")!=std::string::npos||path.find("gnb")!=std::string::npos||path.find("gNB")!=std::string::npos) dlBytes+=bytes; else {ulBytes+=bytes/2; dlBytes+=bytes/2;}} if(hoStartSignals.count(signalID)){hoActive=true; currentNextHoS=0.0;} if(hoEndSignals.count(signalID)){hoActive=false; currentNextHoS=2.0;}}
void LinkTraceLogger::receiveSignal(cComponent*,simsignal_t signalID,long,cObject*){if(signalID==kfginsHoStartSig){hoActive=true; currentNextHoS=0.0;} else if(signalID==kfginsHoEndSig){hoActive=false; currentNextHoS=2.0;}}
void LinkTraceLogger::receiveSignal(cComponent*,simsignal_t signalID,double value,cObject*){if(signalID==kfginsNextHoSig) currentNextHoS=std::max(0.0,value); else if(signalID==kfginsMecQueueDelaySig) currentMecQueueS=std::max(0.0,value);}
void LinkTraceLogger::writeHeader(){out<<"time,vehicle_id,uplink_mbps,downlink_mbps,mec_queue_s,next_ho_s,ho_active\n";}
void LinkTraceLogger::writeRow(){double uplinkMbps=(ulBytes*8.0)/std::max(1e-9,interval)/1e6; double downlinkMbps=(dlBytes*8.0)/std::max(1e-9,interval)/1e6; if(uplinkMbps<0.1) uplinkMbps=4.0; if(downlinkMbps<0.1) downlinkMbps=8.0; out<<simTime().dbl()<<",veh0,"<<uplinkMbps<<","<<downlinkMbps<<","<<currentMecQueueS<<","<<currentNextHoS<<","<<(hoActive?1:0)<<"\n"; ulBytes=0; dlBytes=0;}
void LinkTraceLogger::handleMessage(cMessage *msg){if(msg==timer){writeRow(); scheduleAt(simTime()+interval,timer);}}
void LinkTraceLogger::finish(){if(timer){cancelAndDelete(timer); timer=nullptr;} if(out.is_open()) out.close();}
